import logging
import uuid
from collections import deque
from typing import Any, Dict
from uuid import UUID

from typing_extensions import override

from flink_agents.api.event import Event, InputEvent, OutputEvent
from flink_agents.api.workflow import Workflow
from flink_agents.api.workflow_runner import WorkflowRunner
from flink_agents.api.workflow_runner_context import WorkflowRunnerContext
from flink_agents.plan.workflow_plan import WorkflowPlan

logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)


class LocalRunnerContext(WorkflowRunnerContext):
    """Implementation of WorkflowRunnerContext for local workflow execution.

    Attributes:
    ----------
    __workflow_plan : WorkflowPlan
        Internal workflow plan for this context.
    __id : UUID
        Unique identifier for the context.
    events : deque[Event]
        Queue of events to be processed in this context.
    outputs : deque[Any]
        Queue of outputs generated by workflow execution.
    """

    __workflow_plan: WorkflowPlan
    __id: UUID
    events: deque[Event]
    outputs: deque[Any]

    def __init__(self, workflow_plan: WorkflowPlan, id: UUID) -> None:
        """Initialize a new session with the given workflow and ID.

        Parameters
        ----------
        workflow : Workflow
            Workflow plan used for this context.
        id : UUID
            Unique context identifier. If None, a new UUID will be generated.
        """
        self.__workflow_plan = workflow_plan
        if id is None:
            id = uuid.uuid4()
        self.__id = id
        self.events = deque()
        self.outputs = deque()

    @property
    def session_id(self) -> UUID:
        """Get the unique identifier for this context.

        Returns:
        -------
        UUID
            The session ID.
        """
        return self.__id

    @override
    def send_event(self, event: Event) -> None:
        """Send an event to the context's event queue and log it.

        Parameters
        ----------
        event : Event
            The event to be added to the queue.
        """
        logger.info("session_id: %s, send_event: %s", self.__id, event)
        self.events.append(event)

    def add_output(self, output: Any) -> None:
        """Add an output generate by workflow execution to the context.

        Parameters
        ----------
        output : Any
            The output to be added to the queue.
        """
        self.outputs.append(output)

    def get_outputs(self) -> deque[Any]:
        """Add an output generate by workflow execution to the context.

        Returns:
        -------
        deque[Any]
            The outputs generated by workflow execution on this context.
        """
        return self.outputs

    def clear_output(self) -> None:
        """Clear outputs stored in this context."""
        self.outputs.clear()


class LocalRunner(WorkflowRunner):
    """Workflow runner implementation for local execution, which is
    convenient for debugging.

    Attributes:
    ----------
    __workflow_plan : WorkflowPlan
        Internal workflow plan.
    __sessions : dict[UUID, LocalRunnerContext]
        Dictionary of active sessions indexed by session ID.
    """

    __workflow_plan: WorkflowPlan
    __sessions: dict[UUID, LocalRunnerContext]

    def __init__(self, workflow: Workflow) -> None:
        """Initialize the runner with the provided workflow.

        Parameters
        ----------
        workflow : flink_agent_api.workflow.Workflow
            The workflow class to convert and run.
        """
        self.__workflow_plan = WorkflowPlan.from_workflow(workflow)
        self.__sessions = {}

    @override
    def run(self, session_id: UUID = 0, **kwargs: Dict[str, Any]) -> UUID:
        """Execute the workflow for a specific session.

        Parameters
        ----------
        session_id : int | UUID, optional
            - 0: Use default session
            - -1: Create new session with random UUID
            - UUID: Use specified session
        **kwargs : dict[str, Any]
            Initial parameters to set on the StartEvent.

        Returns:
        -------
        UUID
            The session ID that was executed.
        """
        if session_id == -1:
            session_id = uuid.uuid4()

        if session_id not in self.__sessions:
            self.__sessions[session_id] = LocalRunnerContext(self.__workflow_plan, session_id)
        session = self.__sessions[session_id]

        input_event = InputEvent(input=kwargs['input'])
        for k, v in kwargs.items():
            input_event.__setattr__(k, v)
        session.send_event(input_event)

        while len(session.events) > 0:
            event = session.events.popleft()
            if isinstance(event, OutputEvent):
                session.add_output(event.output)
                continue
            for action in self.__workflow_plan.get_actions(type(event)):
                logger.info(
                    "session_id: %s, performing action: %s", session_id, action.name
                )
                action.exec(event, session)
        return session_id

    def get_outputs(self, session_id: UUID) -> deque[Any]:
        """Obtain the workflow output for a specific session.

        Returns:
        -------
        Any
            The workflow output.
        """
        return self.__sessions[session_id].get_outputs()


def get_workflow_runner(workflow: Workflow) -> WorkflowRunner:
    """Factory function to create a local workflow runner.

    Parameters
    ----------
    workflow : Workflow
        The workflow to be executed.

    Returns:
    -------
    WorkflowRunner
        A configured workflow runner instance.
    """
    return LocalRunner(workflow)
