/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.flink.agents.runtime.actionstate;

import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.apache.flink.agents.api.Event;
import org.apache.flink.agents.api.InputEvent;
import org.apache.flink.agents.api.OutputEvent;
import org.apache.flink.agents.plan.AgentConfiguration;
import org.apache.flink.agents.plan.actions.Action;
import org.apache.fluss.client.Connection;
import org.apache.fluss.client.ConnectionFactory;
import org.apache.fluss.client.admin.Admin;
import org.apache.fluss.client.lookup.LookupResult;
import org.apache.fluss.client.lookup.Lookuper;
import org.apache.fluss.client.table.Table;
import org.apache.fluss.client.table.writer.UpsertWriter;
import org.apache.fluss.config.Configuration;
import org.apache.fluss.metadata.DatabaseDescriptor;
import org.apache.fluss.metadata.Schema;
import org.apache.fluss.metadata.TableDescriptor;
import org.apache.fluss.metadata.TablePath;
import org.apache.fluss.row.BinaryString;
import org.apache.fluss.row.GenericRow;
import org.apache.fluss.row.InternalRow;
import org.apache.fluss.types.DataTypes;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.apache.flink.agents.api.configuration.AgentConfigOptions.FLUSS_ACTION_STATE_DATABASE;
import static org.apache.flink.agents.api.configuration.AgentConfigOptions.FLUSS_ACTION_STATE_TABLE;
import static org.apache.flink.agents.api.configuration.AgentConfigOptions.FLUSS_ACTION_STATE_TABLE_BUCKETS;
import static org.apache.flink.agents.api.configuration.AgentConfigOptions.FLUSS_BOOTSTRAP_SERVERS;
import static org.apache.flink.agents.api.configuration.AgentConfigOptions.FLUSS_SASL_JAAS_CONFIG;
import static org.apache.flink.agents.api.configuration.AgentConfigOptions.FLUSS_SASL_MECHANISM;
import static org.apache.flink.agents.api.configuration.AgentConfigOptions.FLUSS_SASL_PASSWORD;
import static org.apache.flink.agents.api.configuration.AgentConfigOptions.FLUSS_SASL_USERNAME;
import static org.apache.flink.agents.api.configuration.AgentConfigOptions.FLUSS_SECURITY_PROTOCOL;
import static org.apache.flink.agents.runtime.actionstate.ActionStateUtil.generateKey;

/**
 * An implementation of {@link ActionStateStore} that uses Apache Fluss as the backend storage for
 * action states. Fluss provides a primary key table with KV point lookup capability, eliminating
 * the need for in-memory state rebuilding during recovery.
 *
 * <p>Compared to the Kafka-based implementation:
 *
 * <ul>
 *   <li><b>Recovery</b>: No sequential consumption needed; direct KV point lookup (O(1)).
 *   <li><b>Memory</b>: No in-memory cache required; on-demand queries only.
 *   <li><b>Write</b>: In-place upsert instead of append-only log.
 * </ul>
 *
 * <p>The Fluss table schema:
 *
 * <pre>
 * state_key   STRING   -- Primary key, generated by ActionStateUtil.generateKey()
 * state_payload BYTES  -- ActionState JSON serialized bytes
 * seq_num     BIGINT   -- Sequence number for pruneState()
 * agent_key   STRING   -- Original key for prefix-based cleanup
 * completed   BOOLEAN  -- Whether action completed
 * updated_at  BIGINT   -- Last update timestamp
 * </pre>
 */
public class FlussActionStateStore implements ActionStateStore {

    private static final Logger LOG = LoggerFactory.getLogger(FlussActionStateStore.class);
    private static final ObjectMapper OBJECT_MAPPER = createObjectMapper();

    /** Creates and configures the ObjectMapper for ActionState serialization. */
    private static ObjectMapper createObjectMapper() {
        ObjectMapper mapper = new ObjectMapper();
        // Add type information for polymorphic Event deserialization
        mapper.addMixIn(Event.class, EventTypeInfoMixin.class);
        mapper.addMixIn(InputEvent.class, EventTypeInfoMixin.class);
        mapper.addMixIn(OutputEvent.class, EventTypeInfoMixin.class);
        return mapper;
    }

    /** Mixin to add type information for Event hierarchy. */
    @JsonTypeInfo(
            use = JsonTypeInfo.Id.CLASS,
            include = JsonTypeInfo.As.PROPERTY,
            property = "@class")
    abstract static class EventTypeInfoMixin {}

    // Column indices in the Fluss table schema
    private static final int COL_STATE_KEY = 0;
    private static final int COL_STATE_PAYLOAD = 1;
    private static final int COL_SEQ_NUM = 2;
    private static final int COL_AGENT_KEY = 3;
    private static final int COL_COMPLETED = 4;
    private static final int COL_UPDATED_AT = 5;
    private static final int NUM_COLUMNS = 6;

    private final AgentConfiguration agentConfiguration;
    private final String databaseName;
    private final String tableName;
    private final TablePath tablePath;

    private final Connection connection;
    private final Table table;
    private final UpsertWriter writer;
    private final Lookuper lookuper;

    /**
     * Tracks the mapping from agent key to its associated state keys. This is needed because
     * pruneState() needs to delete by agent key prefix, and Fluss primary key lookup requires exact
     * key match.
     */
    private final Map<String, Map<String, Long>> agentKeyToStateKeys;

    public FlussActionStateStore(AgentConfiguration agentConfiguration) {
        this.agentConfiguration = agentConfiguration;
        this.databaseName = agentConfiguration.get(FLUSS_ACTION_STATE_DATABASE);
        this.tableName = agentConfiguration.get(FLUSS_ACTION_STATE_TABLE);
        this.tablePath = TablePath.of(databaseName, tableName);
        this.agentKeyToStateKeys = new HashMap<>();

        // Create Fluss connection
        Configuration flussConf = new Configuration();
        flussConf.setString("bootstrap.servers", agentConfiguration.get(FLUSS_BOOTSTRAP_SERVERS));

        // Security / authentication config
        String securityProtocol = agentConfiguration.get(FLUSS_SECURITY_PROTOCOL);
        if (securityProtocol != null) {
            flussConf.setString("client.security.protocol", securityProtocol);
        }
        String saslMechanism = agentConfiguration.get(FLUSS_SASL_MECHANISM);
        if (saslMechanism != null) {
            flussConf.setString("client.security.sasl.mechanism", saslMechanism);
        }
        String jaasConfig = agentConfiguration.get(FLUSS_SASL_JAAS_CONFIG);
        if (jaasConfig != null) {
            flussConf.setString("client.security.sasl.jaas.config", jaasConfig);
        }
        String username = agentConfiguration.get(FLUSS_SASL_USERNAME);
        if (username != null) {
            flussConf.setString("client.security.sasl.username", username);
        }
        String password = agentConfiguration.get(FLUSS_SASL_PASSWORD);
        if (password != null) {
            flussConf.setString("client.security.sasl.password", password);
        }

        this.connection = ConnectionFactory.createConnection(flussConf);

        // Ensure database and table exist
        maybeCreateDatabaseAndTable();

        // Get table client and create writer/lookuper
        this.table = connection.getTable(tablePath);
        this.writer = table.newUpsert().createWriter();
        this.lookuper = table.newLookup().createLookuper();

        LOG.info("Initialized FlussActionStateStore with table: {}.{}", databaseName, tableName);
    }

    @Override
    public void put(Object key, long seqNum, Action action, Event event, ActionState state)
            throws Exception {
        String stateKey = generateKey(key, seqNum, action, event);
        byte[] payload = OBJECT_MAPPER.writeValueAsBytes(state);

        GenericRow row = new GenericRow(NUM_COLUMNS);
        row.setField(COL_STATE_KEY, BinaryString.fromString(stateKey));
        row.setField(COL_STATE_PAYLOAD, payload);
        row.setField(COL_SEQ_NUM, seqNum);
        row.setField(COL_AGENT_KEY, BinaryString.fromString(key.toString()));
        row.setField(COL_COMPLETED, state.isCompleted());
        row.setField(COL_UPDATED_AT, System.currentTimeMillis());

        // Synchronous write to ensure durability before returning.
        // This is critical for the Reconcile pattern where PENDING slots must be
        // persisted before call() executes.
        writer.upsert(row).get();

        // Track the agent key -> state key mapping for pruneState()
        agentKeyToStateKeys
                .computeIfAbsent(key.toString(), k -> new HashMap<>())
                .put(stateKey, seqNum);

        LOG.debug(
                "Stored action state to Fluss: key={}, isCompleted={}",
                stateKey,
                state.isCompleted());
    }

    @Override
    public ActionState get(Object key, long seqNum, Action action, Event event) throws Exception {
        String stateKey = generateKey(key, seqNum, action, event);

        LOG.debug("Looking up action state from Fluss: key={}, seqNum={}", key, seqNum);

        GenericRow lookupKey = new GenericRow(1);
        lookupKey.setField(0, BinaryString.fromString(stateKey));

        LookupResult result = lookuper.lookup(lookupKey).get();
        InternalRow row = result.getSingletonRow();

        if (row == null) {
            LOG.debug("Action state not found in Fluss: stateKey={}", stateKey);
            return null;
        }

        byte[] payload = row.getBytes(COL_STATE_PAYLOAD);
        ActionState state = OBJECT_MAPPER.readValue(payload, ActionState.class);

        // Rebuild the agentKeyToStateKeys mapping on read.
        // This is critical after recovery: since rebuildState() is a no-op, the mapping
        // is empty. Without this, pruneState() would silently skip cleanup for any state
        // that was written before the restart, causing unbounded table growth.
        agentKeyToStateKeys
                .computeIfAbsent(key.toString(), k -> new HashMap<>())
                .put(stateKey, seqNum);

        LOG.debug(
                "Found action state in Fluss: key={}, isCompleted={}",
                stateKey,
                state.isCompleted());
        return state;
    }

    /**
     * No-op for Fluss backend. Unlike the Kafka implementation which must consume from offsets to
     * rebuild an in-memory HashMap, Fluss's KV table is inherently persistent. Each {@link #get}
     * call performs a direct point lookup, so no in-memory state needs to be rebuilt.
     */
    @Override
    public void rebuildState(List<Object> recoveryMarkers) {
        LOG.info(
                "Fluss backend: rebuildState is a no-op (KV table is persistent). "
                        + "Recovery markers: {}",
                recoveryMarkers.size());
    }

    @Override
    public void pruneState(Object key, long seqNum) {
        LOG.debug("Pruning state for key: {} up to sequence number: {}", key, seqNum);

        Map<String, Long> stateKeys = agentKeyToStateKeys.get(key.toString());
        if (stateKeys == null) {
            return;
        }

        stateKeys
                .entrySet()
                .removeIf(
                        entry -> {
                            if (entry.getValue() <= seqNum) {
                                try {
                                    GenericRow deleteRow = new GenericRow(NUM_COLUMNS);
                                    deleteRow.setField(
                                            COL_STATE_KEY, BinaryString.fromString(entry.getKey()));
                                    writer.delete(deleteRow).get();
                                    LOG.debug("Pruned state key: {}", entry.getKey());
                                } catch (Exception e) {
                                    LOG.warn(
                                            "Failed to delete state key during pruning: {}",
                                            entry.getKey(),
                                            e);
                                }
                                return true;
                            }
                            return false;
                        });

        // Remove agent key entry if no more state keys
        if (stateKeys.isEmpty()) {
            agentKeyToStateKeys.remove(key.toString());
        }

        // Flush to ensure deletes are visible to the lookuper
        try {
            writer.flush();
        } catch (Exception e) {
            LOG.warn("Failed to flush writer after pruning", e);
        }

        LOG.debug("Pruned state for key: {} up to sequence number: {}", key, seqNum);
    }

    /**
     * Returns null because the Fluss KV table is persistent and does not need recovery markers.
     * Unlike Kafka which uses partition end offsets as markers, Fluss's point lookup works directly
     * without any positional information.
     */
    @Override
    public Object getRecoveryMarker() {
        return null;
    }

    @Override
    public void close() throws Exception {
        Exception firstException = null;

        try {
            if (writer != null) {
                writer.flush();
            }
        } catch (Exception e) {
            firstException = e;
        }

        try {
            if (table != null) {
                table.close();
            }
        } catch (Exception e) {
            if (firstException == null) {
                firstException = e;
            }
        }

        try {
            if (connection != null) {
                connection.close();
            }
        } catch (Exception e) {
            if (firstException == null) {
                firstException = e;
            }
        }

        if (firstException != null) {
            throw firstException;
        }
    }

    private void maybeCreateDatabaseAndTable() {
        try (Admin admin = connection.getAdmin()) {
            // Create database if not exists
            if (!admin.databaseExists(databaseName).get()) {
                admin.createDatabase(databaseName, DatabaseDescriptor.EMPTY, true).get();
                LOG.info("Created Fluss database: {}", databaseName);
            }

            // Create table if not exists
            if (!admin.tableExists(tablePath).get()) {
                Schema schema =
                        Schema.newBuilder()
                                .column("state_key", DataTypes.STRING())
                                .column("state_payload", DataTypes.BYTES())
                                .column("seq_num", DataTypes.BIGINT())
                                .column("agent_key", DataTypes.STRING())
                                .column("completed", DataTypes.BOOLEAN())
                                .column("updated_at", DataTypes.BIGINT())
                                .primaryKey("state_key")
                                .build();

                int buckets = agentConfiguration.get(FLUSS_ACTION_STATE_TABLE_BUCKETS);
                TableDescriptor descriptor =
                        TableDescriptor.builder()
                                .schema(schema)
                                .distributedBy(buckets, "state_key")
                                .comment("Flink Agents action state store")
                                .build();

                admin.createTable(tablePath, descriptor, true).get();
                LOG.info("Created Fluss table: {}", tablePath);
            } else {
                LOG.info("Fluss table {} already exists", tablePath);
            }
        } catch (Exception e) {
            LOG.error(
                    "Failed to create or verify Fluss database/table: {}.{}",
                    databaseName,
                    tableName,
                    e);
            throw new RuntimeException("Failed to create or verify Fluss database/table", e);
        }
    }
}
