from abc import ABC
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


class Event(BaseModel, ABC, extra="allow"):
    """Base class for all event types in the system.

    Attributes:
    ----------
    id : UUID
        Unique identifier for the event, automatically generated using uuid4.
    """

    id: UUID = Field(default_factory=uuid4)


class InputEvent(Event):
    """Event generated by the framework, carrying an input data that
    arrives at the workflow.
    """

    input: str


class OutputEvent(Event):
    """Event representing a result from workflow. By generating an OutputEvent,
    actions can emit output data.

    Attributes:
    ----------
    isLegal : bool
        Is the result legal or not.
    result : str
        The final result returned by the workflow.
    """

    isLegal: bool
    result: str
