from abc import ABC, abstractmethod
from collections import deque
from typing import Any

from flink_agents.api.event import Event


class WorkflowRunnerContext(ABC):
    """Abstract base class providing context for workflow execution.

    This context provides access to event handling, session management,
    and external resources.
    """

    @abstractmethod
    def send_event(self, event: Event) -> None:
        """Send an event to the workflow for processing.

        Parameters
        ----------
        event : Event
            The event to be processed by the workflow system.
        """

    @abstractmethod
    def add_output(self, output: Any) -> None:
        """Add an output generate by workflow execution to the context.

        Parameters
        ----------
        output : Any
            The output to be added to the queue.
        """

    @abstractmethod
    def get_outputs(self) -> deque[Any]:
        """Get outputs stored in this context.

        Returns:
        -------
        deque[Any]
            The outputs generated by workflow execution on this context.
        """

    @abstractmethod
    def clear_output(self) -> None:
        """Clear outputs stored in this context."""
